@startuml
'https://plantuml.com/class-diagram

class Main{
    +static void main(String[] args)
}

class Chill{
    -TextUI ui
    -FileIO io
    +seriesList
    +movieList
    -User currentUser
    +saveMedia(Media m)
    +watchMedia(Media m)
    +removeMedia(Media m)
    -searchByName(String query)
    -searchByRating(double rating)
    -searchByCategory(String category)
}

package "util"{
    Interface IO{
        -Scanner scanner
    }

    class FileIO implements IO{
        +ArrayList<User> users
        -loadList(File mediaList)
        -saveCredentials(User u)
        -createUser(String username,String password)
        -login(String username,String password)
    }

    class TextUI{
        -Scanner scanner
        +displayMessage(String msg)
        -displayWatchedMedia(ArrayList<Media>)
        -displaySavedMedia(ArrayList<Media>)
    }
}

package "model"{
    abstract class Media{
        -String title
        -double rating
        -String categories
        +Media(String title,double rating,String categories)
        +getTitle()
        +getRating()
        +getCategories()
    }

    class Movie extends Media{
        -int year
        +Movie(String title,double rating,String categories,int year)
    }

    class Series extends Media{
        -int startYear
        -int endYear
        -ArrayList<String> seasonsAndEpisodes
        +Series(String title,double rating,String categories,int startYear,int endYear,ArrayList<String> seasonsAndEpisodes)
    }

    class User{
        -String username
        -String password
        -int age
        +ArrayList<Media> savedMedia
        +ArrayList<Media> watchedMedia
        +User(String username,String password,int age)
    }
}

Main *-- Chill
Chill *-- TextUI
Chill *-- User
Chill *-- Media
Chill *-- IO


@enduml